package universidadgrupo48.Vistas;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import universidadgrupo48.AccesoDeDatos.AlumnoData;
import universidadgrupo48.AccesoDeDatos.InscripcionData;
import universidadgrupo48.Entidades.Alumno;
import universidadgrupo48.Entidades.Materia;

public class ManejoDeInscripciones extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel(){
    
        public boolean isCellEditable(int f,int c){
        //si pongo false entonces las celdas no son editables
            return false;  
        }
    };
    /**
     * Creates new form manejoDeInscripciones
     */
    public ManejoDeInscripciones() {
        initComponents();
        armarCabecera();
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbAlumno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jRBinscriptas = new javax.swing.JRadioButton();
        jRBnoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTmateria = new javax.swing.JTable();
        jBinscribir = new javax.swing.JButton();
        jBanularInscripcion = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Seleccione un alumno");

        jcbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Listado de Materias");

        jRBinscriptas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBinscriptasMouseClicked(evt);
            }
        });
        jRBinscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBinscriptasActionPerformed(evt);
            }
        });

        jRBnoInscriptas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBnoInscriptasMouseClicked(evt);
            }
        });
        jRBnoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBnoInscriptasActionPerformed(evt);
            }
        });

        jTmateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Año"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTmateria);

        jBinscribir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBinscribir.setForeground(new java.awt.Color(255, 153, 255));
        jBinscribir.setText("Inscribir");

        jBanularInscripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBanularInscripcion.setForeground(new java.awt.Color(255, 153, 255));
        jBanularInscripcion.setText("Anular Inscripcion");

        jBsalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(255, 153, 255));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Materias Inscriptas");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Materioas no Inscriptas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBinscribir)
                                    .addGap(168, 168, 168)
                                    .addComponent(jBanularInscripcion)
                                    .addGap(117, 117, 117)
                                    .addComponent(jBsalir))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jRBinscriptas)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRBnoInscriptas)
                                        .addGap(274, 274, 274))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(218, 218, 218)
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(396, 396, 396)
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addGap(78, 78, 78)
                            .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBinscriptas)
                    .addComponent(jLabel4)
                    .addComponent(jRBnoInscriptas)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBinscribir)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBanularInscripcion)
                            .addComponent(jBsalir))
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jRBinscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBinscriptasActionPerformed
        //setVisible(false);
        if (jRBnoInscriptas.isSelected() == true){
            InscripcionData insData = new InscripcionData();
            Alumno alu = (Alumno)jcbAlumno.getSelectedItem();
            Materia mat = new Materia();
            insData.obtenerMateriaNoCursada(alu.getIdAlumno());
        
            for (Materia materia : insData.obtenerMateriaNoCursada(alu.getIdAlumno())){
                modelo.addRow(new Object[]{
                    materia.getIdMateria(), 
                    materia.getNombre(), 
                    materia.getAnioMateria()
                });
            }
        }
    }//GEN-LAST:event_jRBinscriptasActionPerformed

    private void jRBnoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBnoInscriptasActionPerformed
        
        if (jRBinscriptas.isSelected() == true){
            InscripcionData insData = new InscripcionData();
            Alumno alu = (Alumno)jcbAlumno.getSelectedItem();
            Materia mat = new Materia();
            insData.obtenerMateriasCursadas(alu.getIdAlumno());
        
            for (Materia materia : insData.obtenerMateriasCursadas(alu.getIdAlumno())){
                modelo.addRow(new Object[]{
                    materia.getIdMateria(), 
                    materia.getNombre(), 
                    materia.getAnioMateria()
                });
            } 
        } else {
            //setVisible(false);
        }
    }//GEN-LAST:event_jRBnoInscriptasActionPerformed

    private void jcbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jcbAlumnoActionPerformed

    private void jRBinscriptasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBinscriptasMouseClicked
        // TODO add your handling code here:
        
        
        if (jRBinscriptas.isSelected() == true){
        InscripcionData insData = new InscripcionData();
        Alumno alu = (Alumno)jcbAlumno.getSelectedItem();
        
        insData.obtenerMateriasCursadas(alu.getIdAlumno());
        }
    }//GEN-LAST:event_jRBinscriptasMouseClicked

    private void jRBnoInscriptasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBnoInscriptasMouseClicked
        // TODO add your handling code here:
        /*if (jRBinscriptas.isSelected() == true){
        InscripcionData insData = new InscripcionData();
        Alumno alu = (Alumno)jcbAlumno.getSelectedItem();
        Materia mat = new Materia();
        insData.obtenerMateriaNoCursada(alu.getIdAlumno());
        
        for (Materia materia : insData.obtenerMateriaNoCursada(alu.getIdAlumno())){
            modelo.addRow(new Object[]{materia.getIdMateria(), materia.getNombre(), materia.getAnioMateria()});
        
        }
        }*/
    }//GEN-LAST:event_jRBnoInscriptasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBanularInscripcion;
    private javax.swing.JButton jBinscribir;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRBinscriptas;
    private javax.swing.JRadioButton jRBnoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTmateria;
    private javax.swing.JComboBox<Alumno> jcbAlumno;
    // End of variables declaration//GEN-END:variables
    private void armarCabecera(){
    
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");
    
        jTmateria.setModel(modelo);
    }
    
    private void cargarComboBox(){
        Alumno alum = new Alumno();     
        AlumnoData alu = new AlumnoData();
    
        for(Alumno alumn : alu.listarAlumno()){
            jcbAlumno.addItem(alumn);
        }
    }
}
